"use client";

import { PlayIcon } from "@heroicons/react/24/solid";
import { useState } from "react";

export default function About() {
	const [isVideoPlaying, setIsVideoPlaying] = useState(false);

	return (
		<div className="bg-[#0a0a0a] py-24 sm:py-32">
			<div className="mx-auto max-w-7xl px-6 lg:px-8">
				<div className="mx-auto max-w-2xl lg:mx-0">
					<h2 className="text-base font-semibold leading-7 text-indigo-400">
						Our Story
					</h2>
					<p className="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">
						Democratizing backend development
					</p>
					<p className="mt-6 text-lg leading-8 text-gray-300">
						We believe that building APIs shouldn't require months
						of development or deep technical expertise. ThinCrust
						was born from the frustration of watching great ideas
						get stuck in development bottlenecks.
					</p>
				</div>

				<div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none">
					<div className="grid max-w-xl grid-cols-1 gap-8 lg:max-w-none lg:grid-cols-2">
						<div>
							<h3 className="text-xl font-bold leading-8 text-white">
								Visual-first approach
							</h3>
							<p className="mt-4 text-base leading-7 text-gray-300">
								Our drag-and-drop interface lets you design
								complex database schemas and API logic without
								writing a single line of code. Connect tables,
								define relationships, and set up authentication
								flows visually.
							</p>
							<h3 className="mt-8 text-xl font-bold leading-8 text-white">
								Production-ready from day one
							</h3>
							<p className="mt-4 text-base leading-7 text-gray-300">
								Every API generated by ThinCrust follows
								industry best practices for security,
								performance, and scalability. Built-in features
								like rate limiting, caching, and monitoring mean
								your APIs are enterprise-ready from the start.
							</p>
							<h3 className="mt-8 text-xl font-bold leading-8 text-white">
								Developer-friendly
							</h3>
							<p className="mt-4 text-base leading-7 text-gray-300">
								When you need more control, export clean,
								well-documented code in your preferred
								framework. Our platform enhances developer
								productivity rather than replacing developers.
							</p>
						</div>

						<div className="relative">
							<div className="aspect-[16/9] overflow-hidden rounded-xl bg-gray-900 shadow-xl lg:aspect-[3/2]">
								{!isVideoPlaying ? (
									<div className="relative h-full">
										<img
											alt="ThinCrust API Builder interface showing visual endpoint configuration"
											src="https://tailwindcss.com/plus-assets/img/component-images/dark-project-app-screenshot.png"
											className="h-full w-full object-cover"
										/>
										<div className="absolute inset-0 flex items-center justify-center bg-black/30">
											<button
												onClick={() =>
													setIsVideoPlaying(true)
												}
												className="flex h-16 w-16 items-center justify-center rounded-full bg-white/20 backdrop-blur-sm transition-all hover:bg-white/30 hover:scale-110"
											>
												<PlayIcon className="h-8 w-8 text-white ml-1" />
											</button>
										</div>
									</div>
								) : (
									<div className="h-full w-full bg-gray-800 flex items-center justify-center">
										<div className="text-center">
											<PlayIcon className="h-12 w-12 text-gray-400 mx-auto mb-4" />
											<p className="text-gray-400">
												Demo video would play here
											</p>
											<button
												onClick={() =>
													setIsVideoPlaying(false)
												}
												className="mt-4 text-indigo-400 hover:text-indigo-300"
											>
												Back to preview
											</button>
										</div>
									</div>
								)}
							</div>
						</div>
					</div>
				</div>

				<div className="mt-16 border-t border-gray-800 pt-16">
					<div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4">
						<div className="text-center">
							<dt className="text-3xl font-bold tracking-tight text-white">
								50k+
							</dt>
							<dd className="mt-1 text-base leading-6 text-gray-300">
								APIs created
							</dd>
						</div>
						<div className="text-center">
							<dt className="text-3xl font-bold tracking-tight text-white">
								10M+
							</dt>
							<dd className="mt-1 text-base leading-6 text-gray-300">
								Requests served daily
							</dd>
						</div>
						<div className="text-center">
							<dt className="text-3xl font-bold tracking-tight text-white">
								500+
							</dt>
							<dd className="mt-1 text-base leading-6 text-gray-300">
								Companies using ThinCrust
							</dd>
						</div>
						<div className="text-center">
							<dt className="text-3xl font-bold tracking-tight text-white">
								99.9%
							</dt>
							<dd className="mt-1 text-base leading-6 text-gray-300">
								Uptime guarantee
							</dd>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}
